apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-sample
  labels:
    app.kubernetes.io/name: cluster-api-provider-vmware-desktop
    app.kubernetes.io/managed-by: kustomize
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  paused: false
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: talos-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VDCluster
    name: vdcluster-sample