apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: talos-cp
spec:
  version: v1.32.0
  replicas: 1
  infrastructureTemplate:
    kind: VDMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: vdmachinetemplate-sample
    namespace: default
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      strategicPatches:
        - |
          machine:
            install:
              image: factory.talos.dev/installer/a28d86375cf9debe952efbcbe8e2886cf0a174b1f4dd733512600a40334977d7:v1.9.5
              disk: /dev/sda
              extraKernelArgs:
                - net.ifnames=0
            network: 
              interfaces:
                - interface: eth0
                  dhcp: true
                  vip:
                    ip: 172.16.62.140