---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.244.0.0/16"]
  controlPlaneRef:
    kind: TalosControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: ${CLUSTER_NAME}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VDCluster
    name: ${CLUSTER_NAME}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VDCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  controlPlaneEndpoint:
    host: ${CONTROL_PLANE_ENDPOINT_IP}
    port: 6443
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VDMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  template:
    spec:
      templateID: ${TALOS_VM_ID}
      networkConfig: |
        network:
          version: 2
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
spec:
  version: ${KUBERNETES_VERSION}
  replicas: ${CONTROL_PLANE_MACHINE_COUNT=1}
  infrastructureTemplate:
    kind: VDMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    name: ${CLUSTER_NAME}-control-plane
    namespace: ${NAMESPACE}
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      strategicPatches:
        - |
          machine:
            install:
              image: ghcr.io/kodal/talos-installer:v1.11.0
              disk: /dev/sda
            network: 
              interfaces:
                - interface: ens192
                  dhcp: true
                  vip:
                    ip: ${CONTROL_PLANE_ENDPOINT_IP}
            kubelet:
              extraArgs:
                provider-id: "{ provider_id }"
          cluster:
            allowSchedulingOnControlPlanes: ${CONTROL_PLANE_ALLOW_SCHEDULING=true}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: ${CLUSTER_NAME}-worker
  namespace: ${NAMESPACE}
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_MACHINE_COUNT=0}
  template:
    spec:
      clusterName: ${CLUSTER_NAME}
      version: ${KUBERNETES_VERSION}
      bootstrap:
        configRef:
          kind: TalosConfigTemplate
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          name: ${CLUSTER_NAME}-worker
          namespace: ${NAMESPACE}
      infrastructureRef:
        kind: VDMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        name: ${CLUSTER_NAME}-worker
        namespace: ${NAMESPACE}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VDMachineTemplate
metadata:
  name: ${CLUSTER_NAME}-worker
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      templateID: ${TALOS_VM_ID}
      networkConfig: |
        network:
          version: 2
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-worker
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      generateType: worker
      strategicPatches:
        - |
          machine:
            install:
              image: ghcr.io/kodal/talos-installer:v1.11.0
              disk: /dev/sda
            network: 
              interfaces:
                - interface: ens192
                  dhcp: true
            kubelet:
              extraArgs:
                provider-id: "{ provider_id }"
