name: E2E Tests

on:
  workflow_dispatch:

jobs:
  test-e2e:
    name: Run on Self Hosted
    runs-on: self-hosted
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Verify kind installation
        run: kind version

      - name: Running Test e2e
        run: make test-e2e
